<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0q0rYbcT+QNaArxgSBzz'."\n".'vm/UxScK4SvMS/6cJgWvke5ZC6GMGZtITM4hcGKf9vhCwIdgBD5b8vNpWv5vnsE5'."\n".'UdAHD+DRDx53eXrKiG+FcEleCXL4fHtEKPDwlaF8uQFSqhOUqUcAK7sF1EHNUegq'."\n".'3FWBFBAEupuz33lBjgUH5pTUJiRhpbLaVtb0j/4I7StTEWXmn94ZYkNUEr1TyqFn'."\n".'rA9SA1GFQhQsdn3geGdCtdgO2g0KDa3yx74UbEfNsCkKjwosHQy3uTL9o0BcMWcq'."\n".'AdFo8QEOHUn6tzfTPa67lW+jMxSYJ6SEfWoY0v+yaILtQhyJbbVPSeyuj8cmZz58'."\n".'3QIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
