<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1plINW9\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1plINW9/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container1plINW9.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container1plINW9\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container1plINW9\appAppKernelProdContainer([
    'container.build_hash' => '1plINW9',
    'container.build_id' => '1a90d545',
    'container.build_time' => 1695314047,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1plINW9');
