<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9AuFFXP\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9AuFFXP/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container9AuFFXP.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container9AuFFXP\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container9AuFFXP\appAppKernelProdContainer([
    'container.build_hash' => '9AuFFXP',
    'container.build_id' => '5ac00279',
    'container.build_time' => 1697017782,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9AuFFXP');
