<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_metrics.repository.orders' shared service.

return $this->services['ps_metrics.repository.orders'] = new \PrestaShop\Module\Ps_metrics\Repository\OrderRepository(($this->services['ps_metrics.helper.db'] ?? ($this->services['ps_metrics.helper.db'] = new \PrestaShop\Module\Ps_metrics\Helper\DbHelper())), ($this->services['ps_metrics.helper.shop'] ?? $this->load('getPsMetrics_Helper_ShopService.php')));
