<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTvntu8L\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTvntu8L/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTvntu8L.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTvntu8L\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerTvntu8L\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Tvntu8L',
    'container.build_id' => 'e7cc0c43',
    'container.build_time' => 1696936898,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTvntu8L');
