<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUeH1MX3\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUeH1MX3/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUeH1MX3.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUeH1MX3\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerUeH1MX3\appAppKernelDevDebugContainer([
    'container.build_hash' => 'UeH1MX3',
    'container.build_id' => '4aa9b687',
    'container.build_time' => 1697637604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUeH1MX3');
